import os
import json
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from .base_agent import BaseAgent


class PPTAgent(BaseAgent):
    def __init__(self, llm_provider="gemini"):
        super().__init__(llm_provider)
        self.name = "PowerPoint Agent"

    def run(self, task: str, **kwargs) -> dict:
        output_path = kwargs.get("output_path", "outputs/output.pptx")
        os.makedirs(os.path.dirname(output_path), exist_ok=True)

        prompt = f"""You are a presentation expert.
Task: {task}
Generate a PowerPoint presentation outline as JSON:
{{
  "title": "Presentation Title",
  "slides": [
    {{"title": "Slide Title", "bullets": ["point 1", "point 2", "point 3"]}},
    ...
  ]
}}
Generate 5-7 slides. Return ONLY valid JSON."""

        raw = self.think(prompt)

        try:
            start = raw.find("{")
            end = raw.rfind("}") + 1
            data = json.loads(raw[start:end])
        except Exception:
            data = {
                "title": "Presentation",
                "slides": [{"title": "Slide 1", "bullets": ["Content here"]}],
            }

        prs = Presentation()
        prs.slide_width = Inches(13.33)
        prs.slide_height = Inches(7.5)

        # Title slide
        title_slide = prs.slides.add_slide(prs.slide_layouts[0])
        title_slide.shapes.title.text = data["title"]
        title_slide.placeholders[1].text = "Generated by Multi-Agent System"

        # Content slides
        for slide_data in data.get("slides", []):
            slide = prs.slides.add_slide(prs.slide_layouts[1])
            slide.shapes.title.text = slide_data["title"]
            tf = slide.placeholders[1].text_frame
            tf.clear()
            for i, bullet in enumerate(slide_data.get("bullets", [])):
                p = tf.add_paragraph() if i > 0 else tf.paragraphs[0]
                p.text = bullet
                p.level = 0

        prs.save(output_path)
        return {
            "output": json.dumps(data, indent=2),
            "file_path": output_path,
            "message": f"PowerPoint created at {output_path}",
        }
